INSERT INTO teams VALUES (1, 'Boltaliðið');
INSERT INTO teams VALUES (2, 'Dripplararnir');
INSERT INTO teams VALUES (3, 'Skotföstu kempurnar');
INSERT INTO teams VALUES (4, 'Markaskorarnir');
INSERT INTO teams VALUES (5, 'Sigurliðið');
INSERT INTO teams VALUES (6, 'Risaeðlurnar');
INSERT INTO teams VALUES (7, 'Framherjarnir');
INSERT INTO teams VALUES (8, 'Fljótu fæturnir');
INSERT INTO teams VALUES (9, 'Vinningshópurinn');
INSERT INTO teams VALUES (10, 'Ósigrandi skotfólkið');
INSERT INTO teams VALUES (11, 'Óhemjurnar');
INSERT INTO teams VALUES (12, 'Hraðaliðið');